#!/bin/sh
# Builds the WebP copies the site actually serves, and the size table that
# lets every <img> declare its real width and height.
#
# For each PNG/JPEG in public/images (the originals stay as the sources):
#   public/images/webp/<name>.webp      full size, for the full-screen viewer
#   public/images/webp/<name>-800.webp  800px wide, for cards and thumbnails
# and src/assets/imageSizes.js with the original [width, height].
#
# Run after adding or replacing an image:  npm run images
# macOS: needs sips (built in) and cwebp (brew install webp).
set -e
cd "$(dirname "$0")/.."
mkdir -p public/images/webp
out=src/assets/imageSizes.js
{
  echo "// Generated by scripts/images.sh. Do not edit by hand."
  echo "// Original [width, height] of each image in public/images."
  echo "const imageSizes = {"
  for f in public/images/*.png public/images/*.jpg public/images/*.jpeg; do
    [ -e "$f" ] || continue
    name=$(basename "$f"); name=${name%.*}
    w=$(sips -g pixelWidth "$f" | awk '/pixelWidth/ {print $2}')
    h=$(sips -g pixelHeight "$f" | awk '/pixelHeight/ {print $2}')
    cwebp -quiet -q 80 -metadata none "$f" -o "public/images/webp/$name.webp"
    if [ "$w" -gt 800 ]; then
      cwebp -quiet -q 80 -metadata none -resize 800 0 "$f" -o "public/images/webp/$name-800.webp"
    else
      cp "public/images/webp/$name.webp" "public/images/webp/$name-800.webp"
    fi
    echo "  '/${f#public/}': [$w, $h],"
  done
  echo "};"
  echo ""
  echo "export default imageSizes;"
} > "$out"
echo "wrote $out and public/images/webp/"
